site_name: SSVproff Documentation
site_description: Монорепозиторий для управления файлами, автоматизации, безопасности и версионирования
site_author: Serg2206
site_url: https://serg2206.github.io/SSVproff/

# Repository
repo_name: Serg2206/SSVproff
repo_url: https://github.com/Serg2206/SSVproff
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 SSVproff Team

# Theme configuration
theme:
  name: material
  language: ru
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # Table of contents
    - toc.follow
    - toc.integrate
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Content
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    # Header
    - announce.dismiss

# Plugins
plugins:
  - search:
      lang: 
        - ru
        - en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true
  - mermaid2
  # mike для версионирования документации
  # Используется в GitHub Actions для деплоя версий

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra configuration
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Serg2206/SSVproff
      name: GitHub Repository
  analytics:
    feedback:
      title: Эта страница была полезна?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Да, полезна
          data: 1
          note: >-
            Спасибо за обратную связь!
        - icon: material/emoticon-sad-outline
          name: Можно лучше
          data: 0
          note: >- 
            Спасибо! Помогите нам улучшить страницу, создав issue в GitHub.

# Navigation structure
nav:
  - Главная: index.md
  - Быстрый старт:
      - Установка: getting-started/setup.md
      - Конфигурация: getting-started/configuration.md
      - Первые шаги: getting-started/quickstart.md
  - Архитектура:
      - Обзор: architecture.md
      - API модуль: architecture/api.md
      - Web модуль: architecture/web.md
      - Flows: architecture/flows.md
      - ADR:
          - Шаблон: adr/template.md
          - "ADR-0001: Выбор монорепо": adr/0001-monorepo-structure.md
  - Руководство:
      - Использование: guide/usage.md
      - Управление файлами: guide/file-management.md
      - Автоматизация: guide/automation.md
      - Docker: guide/docker.md
  - API Reference:
      - FastAPI: api/fastapi.md
      - Эндпоинты: api/endpoints.md
  - Разработка:
      - Contributing: development/contributing.md
      - Code Style: development/code-style.md
      - Testing: development/testing.md
      - CI/CD: development/ci-cd.md
  - Безопасность: security.md
  - Changelog: changelog.md
