site_name: SSVproff Documentation
site_description: Private repository for file storage, management, automation, security, and versioning
site_author: Serg2206
site_url: https://serg2206.github.io/SSVproff/

repo_name: Serg2206/SSVproff
repo_url: https://github.com/Serg2206/SSVproff

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
      - Setup: setup.md
      - Configuration: configuration.md
  - User Guide:
      - Usage: usage.md
      - File Management: file-management.md
      - Automation: automation.md
  - API Reference: api.md
  - Security: security.md
