name: Pages (Docs + Web)
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'web/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build Docs
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install mkdocs-material
      - run: mkdocs build --strict

      # Build Web
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package.json'
      - name: Install deps
        working-directory: web
        run: npm ci || npm install
      - name: Build web
        working-directory: web
        run: npm run build

      # Prepare gh-pages content
      - name: Prepare publish dir
        run: |
          mkdir -p publish/docs
          mkdir -p publish/web
          cp -r site/* publish/docs/
          cp -r web/out/* publish/web/

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
